const PERCENT_BASE = 100
const QUARTER_DIVISOR = 4

export const PERCENTILE_MEDIUM_THRESHOLD = PERCENT_BASE / 2
export const PERCENTILE_HIGH_THRESHOLD = PERCENT_BASE - (PERCENT_BASE / QUARTER_DIVISOR)
export const PERCENTILE_LOW_THRESHOLD = PERCENT_BASE / QUARTER_DIVISOR
